[oracle]
node_id = "oracle-node-binance-1"
aggregator_url = "http://localhost:50051"
fetch_interval = 10

[sources]
enabled = ["binance"]

[binance]
api_url = "https://api.binance.com/api/v3/ticker/price"
symbol = "BTCUSDT"
timeout = 10
max_retries = 3

[logging]
level = "info"