[oracle]
node_id = "oracle-node-coinbase-1"
aggregator_url = "http://localhost:50051"
fetch_interval = 15

[sources]
enabled = ["coinbase"]

[coinbase]
api_url = "https://api.coinbase.com/v2/exchange-rates"
currency = "BTC"
timeout = 10
max_retries = 3

[logging]
level = "info"